[project]
name = 'Holographic-Entertainment-Rights-Management-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fan-engagement-token]
path = 'contracts/fan-engagement-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.holo-performance-nft]
path = 'contracts/holo-performance-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
